create database customer_behavior;
use customer_behavior;

### Business Questions 

## what is the total revenue generated by male vs female customers 

	select 
		gender,
        sum(purchase_amount) Total_revenue 
	from customer 
    group by 1
    order by  2 desc;
    
    
## which customer used discount but still spent more that average purchase amount4	
	
    select 	
    customer_id,
    purchase_amount
    from customer 
    where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer);
    
## which are the top 5 products with the highest average review rating
	
    select 
		item_purchased,
        round(avg(review_rating),2) Avg_rating
	from customer 
    group by 1
    order by 2 desc
    limit 5;

## compare the average purchase amounts betwen standard and express shiping

	select 
		shipping_type,
        avg(purchase_amount) Avg_amount
	from customer 
    where shipping_type in ("Standard","Express")
    group by 1 
    order by 2 desc;
    
## Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non subscribers
	
    select 
		subscription_status,
        count(customer_id) Total_customers,
        round(avg(purchase_amount),2) Avg_Revenue,
        sum(purchase_amount) Total_Revenue 
	from customer 
    group by 1;
	
## which 5 products have the highest percentage of purchases with discounts applied
	
    select 
		item_purchased,
        round(sum(case when discount_applied = "Yes" then 1 else 0 end) * 100 / count(*),2) discount_rate
	from customer
	group by 1
    order by 2 desc
    limit 5;

## segment customers into new,returning and loyal based on their total number of previous purchases and show the count of each segment

	with customer_type as (
		select 	
			customer_id,previous_purchases,
            case when previous_purchases = 1 then "New"
            when previous_purchases between 2 and 10 then "Returning"
            else "Loyal"
            end customer_segment
		from customer
        )
	select 
		customer_segment,
        count(*) 
	from customer_type
    group by 1;
    
## what are the top 3 most purchased products within each category
	
    with item_counts as (
    select 
		category,
        item_purchased,
        count(customer_id) as total_orders,
        row_number() over(partition by category order by count(customer_id) desc ) as item_rank
	from customer 
    group by 1,2
    )
    
    select item_rank,category,item_purchased,total_orders
    from item_counts
    where item_rank <= 3;
    
## Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
	
    select 
		subscription_status,
        count(customer_id) Repeat_Buyers
        from customer 
        where previous_purchases > 5
        group by 1;
        
## what is the revenue contribution of each age group 	
	
    select 
		age_group,
        sum(purchase_amount) as total_revenue 
        from customer 
        group by 1
        order by 2 desc;
        